import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.scss';
import { COMICO } from './util/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${COMICO.className} ${COMICO.variable}`}>
        {children}
      </body>
    </html>
  );
}
