import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.scss';
import { GENERAL_SANS, GENERAL_SANS_ITALIC, ROWDIES } from './util/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${GENERAL_SANS.className} ${GENERAL_SANS.variable} ${GENERAL_SANS_ITALIC.variable} ${ROWDIES.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
