import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { COMICO, PP_NEUE_MONTREAL } from './util/fonts';
import { Theme } from '@radix-ui/themes';
import '@radix-ui/themes/styles.css';
import './theme-config.css';
import './globals.scss';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${COMICO.className} ${COMICO.variable} ${PP_NEUE_MONTREAL.variable}`}
      >
        <Theme>{children}</Theme>
      </body>
    </html>
  );
}
